(function(){/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
'use strict';var h=this||self;function k(a){if(a&&a!=h)return m(a.document);null===p&&(p=m(h.document));return p}var q=/^[\w+/_-]+[=]{0,2}$/,p=null;function m(a){return(a=a.querySelector&&a.querySelector("script[nonce]"))&&(a=a.nonce||a.getAttribute("nonce"))&&q.test(a)?a:""}function r(a){return a};var t;var u;function w(a,c){this.g=c===x?a:""}w.prototype.toString=function(){return this.g+""};var x={};try{(new self.OffscreenCanvas(0,0)).getContext("2d")}catch(a){};function y(a){this.g=a||h.document||document};function z(a,c,g){a.timeOfStartCall=(new Date).getTime();var d=g||h,n=d.document,b=a.nonce||k(d);b&&!a.nonce&&(a.nonce=b);if("help"==a.flow){a:{var f=["document","location","href"];for(var l=d||h,v=0;v<f.length;v++)if(l=l[f[v]],null==l){f=null;break a}f=l}!a.helpCenterContext&&f&&(a.helpCenterContext=f.substring(0,1200));f=!0;c&&JSON&&JSON.stringify&&(l=JSON.stringify(c),(f=1200>=l.length)&&(a.psdJson=l));f||(c={invalidPsd:!0})}c=[a,c,g];d.GOOGLE_FEEDBACK_START_ARGUMENTS=c;g=a.serverUri||"//www.google.com/tools/feedback";
if(f=d.GOOGLE_FEEDBACK_START)f.apply(d,c);else{d=g+"/load.js?";for(var e in a)c=a[e],(g=null==c)||(g=typeof c,g="object"==g&&null!=c||"function"==g),g||(d+=encodeURIComponent(e)+"="+encodeURIComponent(c)+"&");a=(n?new y(9==n.nodeType?n:n.ownerDocument||n.document):t||(t=new y)).g;e="SCRIPT";"application/xhtml+xml"===a.contentType&&(e=e.toLowerCase());a=a.createElement(e);b&&a.setAttribute("nonce",b);b=d;if(void 0===u)if(e=null,(d=h.trustedTypes)&&d.createPolicy){try{e=d.createPolicy("uf-api#html",
{createHTML:r,createScript:r,createScriptURL:r})}catch(D){h.console&&h.console.error(D.message)}u=e}else u=e;b=(e=u)?e.createScriptURL(b):b;b=new w(b,x);a.src=b instanceof w&&b.constructor===w?b.g:"type_error:TrustedResourceUrl";(b=k(a.ownerDocument&&a.ownerDocument.defaultView))&&a.setAttribute("nonce",b);n.body.appendChild(a)}}var A=["userfeedback","api","startFeedback"],B=h;A[0]in B||"undefined"==typeof B.execScript||B.execScript("var "+A[0]);
for(var C;A.length&&(C=A.shift());)A.length||void 0===z?B[C]&&B[C]!==Object.prototype[C]?B=B[C]:B=B[C]={}:B[C]=z;}).call(this);
